services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cub3d
    image: app
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: .
        target: /app
    # environment:
    #   - ASAN_OPTIONS=detect_leaks=1
    #   - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libasan.so.6